
categoria.validazioneById=select c from Categorie c \
where id = :id and :id like :pattern%

categoria.findByFilter = select c from Categorie c \
where (:id is null or c.id like :id%) 

alim.validazioneById=select a from TipoAlimentazione a \
where id = :id and :id like :pattern%

alim.findByFilter = select a from TipoAlimentazione a \
where (:id is null or a.id like :id%) 

utente.selectByFilter = select u from Utente u \
where (:userName is NULL or u.userName like :userName%) \
and (:nome is NULL or u.nome like :nome%) \
AND (:cognome IS NULL or u.cognome Like :cognome%) \
AND (:role IS NULL OR u.role = :role)  