
categoria.validazioneById=select c from Categorie c \
where id = :id and :id like :pattern%

categoria.findByFilter = select c from Categorie c \
where (:id is null or c.id like :id%) 

alim.validazioneById=select a from TipoAlimentazione a \
where id = :id and :id like :pattern%

alim.findByFilter = select a from TipoAlimentazione a \
where (:id is null or a.id like :id%) 
