spring.application.name=backendVeicoli

logging.level.root=info
logging.level.com.betacom=debug

logging.file.name=./veicoli.log
logging.pattern.console=  %d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\\(%F:%L\\) - %msg%n

server.port=9090
spring.datasource.url=${db_url} 
spring.datasource.username=${db_user}
spring.datasource.password=${db_pwd}

spring.jpa.show-sql = false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hbm2ddl.schema-generation.script.append=false

spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=define.sql
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=drop.sql

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${mail.sender}
spring.mail.password=${mail.password}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/vehicles-market

app.jwt.secret=ctRTPZsqhiKPg2ThA11ikTYdvLHkrb2/rd3AnikFK5/2XtkZVw54YSTY1qFU4QbX7PZPG0eFBTE7jTcEwnZ4Ew==
app.jwt.access-token-expiration-seconds=900
app.jwt.refresh-token-expiration-days=7

keycloak.clientId: vehicles-registration-service
keycloak.clientSecret: ${keycloak.clientSecret}
keycloak.registrationServerUrl=http://localhost:8180
keycloak.registrationRealm=vehicles-market
keycloak.registrationClientId=vehicles-registration-service
keycloak.registrationClientSecret=${keycloak.clientSecret}

app.upload.dir=uploads
app.sender=${mail.sender}
app.clientDomain=${client.domain}
app.resetPassword=resetPassword/
app.scriptBatch=/Users/gerard/scripts/runspringbootbatch.sh
